### ISSUE TITLE
Support packages installed from Python

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-vyper#119]
### Overview

Apparently you can install dependencies from Python now.

https://docs.vyperlang.org/en/latest/structure-of-a-contract.html#searching-for-imports

### Specification

Allow dependencies installed from python to somehow work.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by pcaversaccio** [comment]
An example contract where you want this after installing snekmate via `pip install snekmate`:

```vy
# pragma version ~=0.4.0
from ethereum.ercs import IERC20
from ethereum.ercs import IERC20Detailed
from snekmate.auth import ownable
from snekmate.tokens import erc20


initializes: ownable
initializes: erc20[ownable := ownable]
exports: (
    erc20.owner,
    erc20.IERC20,
    erc20.IERC20Detailed,
    erc20.mint,
    erc20.set_minter,
)


@deploy
def __init__():
    ownable.__init__()
    erc20.__init__("Vyper", "VY", 18, "Vyper", "1")
```

**Comment by pcaversaccio** [comment]
And an example of how verification looks like (see the explorer on the right): https://eth-sepolia.blockscout.com/address/0x97E68f1Dc2e86bc87e3c01e2Df1075859B5a4856

![image](https://github.com/ApeWorX/ape-vyper/assets/25297591/0a2eb9f9-9e5d-4e38-b1cd-2347ad2d7fdb)
