### ISSUE TITLE
Issue using plugin with no compilers installed via VVM

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-vyper#21]
see: https://github.com/ApeWorX/ape/issues/86

**Comment by sabotagebeats** [comment]
steps tried to replicate: 

1) `pyenv virtualenv vypertest && pyenv activate vypertest`
2) `pip install eth-ape ape-vyper`
3) `rm -rf ~/.vvm/*`
4) `brownie bake vyper-token && cd vyper-token`
5) `ape compile`

results:
```
$ ape compile
INFO: Compiling 'contracts/Token.vy'
100%|███████████| 20.4M/20.4M [00:53<00:00, 379kiB/s]
```
```
$ ll .build
total 20
drwxr-xr-x  2 sabotage sabotage  4096 Jul 14 12:08 ./
drwxr-xr-x 10 sabotage sabotage  4096 Jul 14 12:07 ../
-rw-r--r--  1 sabotage sabotage 10713 Jul 14 12:08 __local__.json 
```

I wasn't able to reproduce this.

**Comment by fubuloubu** [comment]
this works now
